### ISSUE TITLE
Rows not filling correctly.

### ISSUE THREAD

**Issue by liamtarpey** [homerjam/angular-gridify#8]
Hi James, 

I have an issue with a certain grid I'm using. It has 5 images and I'm trying to get 3 in one row and 2 in the next.

My options: 

```
minRowLength: 2
perRow: 3
```

Am I missing something obvious? 

I always get 4 image in the top row and one image in the second row that's huge if I set my `minRowLength: 1` or small if i set it to `2`

Trying to debug the code now to find out why this is happening but any help would be appreciated

Thanks :)

**Comment by liamtarpey** [comment]
Think I was breaking this because I was using `averageRatio`

What exactly is it's purpose?

**Comment by homerjam** [comment]
Hi Liam,

Basically `perRow` is used in combination with `averageRatio` to determine when to create a new row. You are probably getting 4 in the first row because the aspect ratios of the tiles are all below the `averageRatio`. If for instance you have mainly portrait images/tiles in your grid then set the `averageRatio` to < 1 and you will get a result closer to the intended `perRow` setting.

`minRowLength` determines when "row filling" should occur - so if there are more than `minRowLength` tiles in the last row then they will be scaled up to fill the row. This is mainly useful with longer rows (more tiles per row) as it makes it look neater - but causes an issue (as you noted) with short rows as they are often way oversized.

Hope that helps. Closing this for now.
